# Generated by Django 5.0 on 2023-12-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreNwsenga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='link',
            field=models.URLField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(default=0, max_length=10, null=True)),
                ('documentation', models.CharField(default='', max_length=350, null=True)),
                ('direction', models.CharField(default='', max_length=255, null=True)),
                ('max_price', models.FloatField(default=0, null=True)),
                ('min_price', models.FloatField(default=0, null=True)),
                ('owner_name', models.CharField(default='', max_length=350, null=True)),
                ('owner_phone', models.CharField(default='', max_length=11, null=True)),
                ('notes', models.TextField(default='', null=True)),
                ('link', models.URLField(default='', null=True)),
                ('fence', models.BooleanField(default=False)),
                ('electric', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('water_depth', models.FloatField(default=0, null=True)),
                ('house', models.BooleanField(default=False)),
                ('tree', models.BooleanField(default=False)),
                ('installment', models.FloatField(default=0, null=True)),
                ('advance_payment', models.FloatField(default=0, null=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreNwsenga.bill')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreNwsenga.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreNwsenga.country')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreNwsenga.neighborhood')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreNwsenga.type')),
            ],
        ),
    ]
