# Generated by Django 5.0 on 2023-12-31 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreNwsenga', '0002_bill_type_neighborhood_link_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
