# Generated by Django 5.0 on 2024-01-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreNwsenga', '0004_alter_buy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='typos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coreNwsenga.type'),
            preserve_default=False,
        ),
    ]
