# Generated by Django 5.0 on 2024-01-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreNwsenga', '0005_buy_typos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='typos',
        ),
    ]
