# Generated by Django 5.0 on 2024-01-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreNwsenga', '0006_remove_buy_typos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
